setup: |
  echo "ğŸŠ All project dependencies have been installed!"
---

# count number of commits in the GitHub repository
- description: Have at least 3 of commits in repository
  check: CountCommits
  options:
    count: 3
